version: '3'
services:
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: wongames
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: wongames
      DATABASE_PASSWORD: wongames123
    volumes:
      - ./app:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    image: postgres:13.1
    environment:
      POSTGRES_DB: wongames
      POSTGRES_USER: wongames
      POSTGRES_PASSWORD: wongames123
    volumes:
      - ./data:/var/lib/postgresql/data